config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  resources :users do
    resources :jokes
  end
  get 'my_jokes', to: 'jokes#my_jokes', as: :my_jokes
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/joke.rb
class Joke < ApplicationRecord
  belongs_to :user
  before_create :send_to_supabase

  private

  def send_to_supabase
    url = URI(ENV['SUPABASE_BASE_URL'].to_s)
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    request = Net::HTTP::Post.new(url, 'Content-Type' => 'application/json', "Prefer" => "return=minimal")
    request['Authorization'] = "Bearer #{ENV['SUPABASE_KEY']}"
    request['apikey'] = "#{ENV['SUPABASE_KEY']}"
    request.body =  { 'content': self.content.to_s, 'user_id': self.user_id.to_s }.to_json
    https.request(request)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jokes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/jokes_controller.rb
require 'uri'
require 'net/http'
class JokesController < ApplicationController
  before_action :authenticate_user!

  def new
    @joke = current_user.jokes.new(content: get_joke, user: current_user)
  end

  def create
    current_user.jokes.create(user: current_user, content: message_params[:content])
  end

  def my_jokes
    @jokes = get_my_jokes
  end

  private
  
  def get_joke
    url = URI(ENV['CHUCK_NORRIS_URL'].to_s)
    response = Net::HTTP.get(url)
    JSON.parse(response)['value']
  end

  def get_my_jokes
    url = URI("#{ENV['SUPABASE_BASE_URL']}?user_id=eq.#{current_user.id}&select=*")
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    request = Net::HTTP::Get.new(url, 'Content-Type' => 'application/json', 'Accept-Encoding' => 'utf-8')
    request['Authorization'] = "Bearer #{ENV['SUPABASE_KEY']}"
    request['apikey'] = "#{ENV['SUPABASE_KEY']}"
    response = https.request(request)
    JSON.parse(response.body)
  end

  def message_params
    params.permit(:content, :authenticity_token, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/home/index.html.erb
<button><%= link_to "Get Jokes", new_user_joke_path(current_user), :method => :get%></button>
<button><%= link_to "My Jokes", my_jokes_path, :method => :get%></button>

<br><br><br><br>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

app/views/jokes/my_jokes.html.erb
<a href="/">Home</a>

<h1>My Jokes</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Content</th>
    </tr>
  </thead>

  <tbody>
    <% @jokes.each do |joke| %>
      <tr>
        <td><%= joke['id'] %></td>
        <td><%= joke['content'] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

app/views/jokes/new.html.erb
<a href="/">Home</a>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<br><br><br><br>

<h1>Chuck Norris Joke :)<h1>
<%= button_to "Refresh Joke", new_user_joke_path(current_user), :method => :get%>
<p><%=@joke.content %></p>

<%= button_to "Favorite", user_jokes_path(content: @joke.content), { controller: "jokes", action: "create", method: :post } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChuckNorris</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>